name: Linux
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup zig
        uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master

      - name: Build (64 bit)
        run: zig build

      - name: Tests (internal)
        run: zig build test

      - name: Tests (standalone scripts)
        working-directory: test
        run: ./test_all.sh
